name: UNSW Timetable Scraper

on:
  schedule:
    # Run every hour at minute 0 (e.g., 1:00, 2:00, 3:00...)
    - cron: "0 * * * *"
  workflow_dispatch: # Allow manual triggering
    inputs:
      test_run:
        description: "Test run (limited courses)"
        required: false
        default: "false"

jobs:
  scrape-timetable:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: backend/scraper/package-lock.json

      - name: Install dependencies
        run: |
          cd backend/scraper
          npm ci

      - name: Setup Chrome for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1 \
            libgbm1 \
            libgcc1 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            lsb-release \
            wget \
            xdg-utils

      - name: Create Firebase service account key
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > backend/scraper/firebase-service-account.json

      - name: Run scraper
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          TEST_RUN: ${{ github.event.inputs.test_run }}
        run: |
          cd backend/scraper
          npm run scrape

      - name: Cleanup
        if: always()
        run: |
          rm -f backend/scraper/firebase-service-account.json
